name: Publish

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set Up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -
        name: Set Up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      -
        name: Install Packages
        run: yarn install
      -
        name: Lint
        run: yarn lint
      -
        name: Download Content
        run: yarn download-content
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      -
        name: Build
        run: yarn build
        env:
          NODE_ENV: production
          PORT: "80"
          URL: https://landonschropp.com
      - 
       name: Publish
       uses: peaceiris/actions-gh-pages@v2
       env:
         PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
         PUBLISH_BRANCH: gh-pages
         PUBLISH_DIR: ./build
