name: Deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Up Node.js
        uses: actions/setup-node@v2
      -
        name: Install Packages
        run: yarn install
      -
        name: Lint
        run: yarn lint
        env:
          NODE_ENV: test
      -
        name: Build
        run: yarn build
        env:
          NODE_ENV: production
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      -
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
